version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
      args:
        BUILD_ENV: dev
    ports:
      - "8090:8090"
      - "5173:5173"
    volumes:
      - ./backend:/pocketbase
      - ./frontend/src:/web/src
    env_file:
      - .env

  prod:
    build:
      context: .
      target: prod
    ports:
      - "8090:8090"
    env_file:
      - .env