#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
root = "."
tmp_dir = "./tmp"

[build]
  cmd = "go build -o ./tmp/air_backend ."
  bin = "./tmp/air_backend"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  follow_symlink = false
  log = "build-errors.log"
  delay = 1000
  stop_on_error = true

[log]
  time = false